# TODO: Ensure all this is correct and up-to-date
generation:
  output: 
    dir: "./flowzero_src/data/synthetic" # Relative to project root
  method: "stochastic" # "stochastic" or "algorithmic" --- stochastic tends to be better and faster

mcgs:
  sims_per_move: 800
  uct_constant: 1.5
  verbose: True
  max_rollout_steps: 2000
  seed: 42

net:
  channels: 64
  res_blocks: 6
  
train:
  batch_size: 512
  lr: 1e-3
  replay_size: 50000

env:
  level: "easy"
  max_steps: 1000
  num_levels: 1000
  render: false
  use_cache: true